import React from "react";
import { Card, CardContent, CardFooter } from "./ui/card";
import Markdown from "./markdown";
import Link from "next/link";

type Props = {
  role: string;
  content: string;
};

const MessageBox = ({ role, content }: Props) => {
  return (
    <Card>
      <CardContent className="p-6 text-sm">
        <Markdown content={content} />
      </CardContent>
      {role !== "user" && (
        <CardFooter className="border-t bg-muted/50 px-4 sm:px-6 py-3 text-xs text-muted-foreground">
          <p className="text-center sm:text-left">
            Disclaimer: The response generated by the AI may not be correct.
            Please visit the official website by clicking on{" "}
            <Link
              href="https://mescoe.mespune.org/"
              className="text-blue-600 underline"
            >
              official site
            </Link>
          </p>
        </CardFooter>
      )}
    </Card>
  );
};

export default MessageBox;
